#The FROM keyword tells Docker which image your image is based on.
FROM daocloud.io/library/ubuntu:latest

#Now, add the python program to the image.
RUN apt-get -y update

#Once the image has the software it needs, you instruct the software to run when the image is loaded.
CMD bash